name: linktree
description: pewriebontal's linktree.

publish_to: "none"

version: 1.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.2
  google_fonts: ^2.0.0
  font_awesome_flutter: ^9.0.0
  dough: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/profile.png