name: Build and Deploy

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.1

    - name: Install and Build 🔧
      uses: subosito/flutter-action@v1
      with:
        channel: dev
    - run: flutter config --enable-web
    - run: flutter pub get
#    - run: flutter test
    - run: flutter build web --web-renderer canvaskit --release

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: build/web
